stages:
  - test
  - build
  - deploy

variables:
  # set docker host to connect to docker in kubernetes
  # DOCKER_HOST: tcp://localhost:2375/
  # DOCKER_DRIVER: overlay2
  # TODO: Set correct certs dir to /certs according to this article: https://about.gitlab.com/2019/07/31/docker-in-docker-with-docker-19-dot-03/
  DOCKER_TLS_CERTDIR: "/certs"

cache:
  key: "lotta-api-deps"
  paths:
    - deps/

services:
  - name: postgres:latest
  - name: rabbitmq:latest
  - name: bitnami/redis:latest
    alias: redis
  - name: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    alias: elasticsearch
    command:
      - "bin/elasticsearch"
      - "-Ediscovery.type=single-node"
      - "-Expack.security.enabled=false"

test:
  stage: test
  image: elixir:1.10.2
  variables:
    MIX_ENV: test
    POSTGRES_PASSWORD: lotta
    POSTGRES_USER: lotta
    POSTGRES_DB: api_test
    REDIS_PASSWORD: lotta
    UGC_S3_COMPAT_ACCESS_KEY_ID: "${S3COMPAT_ACCESS_KEY_ID}"
    UGC_S3_COMPAT_SECRET_ACCESS_KEY: "${S3COMPAT_SECRET_ACCESS_KEY}"
    UGC_S3_COMPAT_ENDPOINT: mp4-dev-ugc.fra1.digitaloceanspaces.com
    UGC_S3_COMPAT_BUCKET: mp4-dev-ugc
  before_script:
    - mix local.hex --force
    - mix local.rebar --force
    - mix deps.get --only test
  script:
    # gitlab k8s-runner has a problem with service hostname exposition
    # https://gitlab.com/gitlab-org/gitlab-runner/issues/2229
    - make tests-ci
  coverage: '/\[TOTAL\]\s+(\d+\.\d+%)$/'

build docker image:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"$(echo -n "$DOCKER_HUB_USER:$DOCKER_HUB_PASSWORD" | base64)\"}}}" > /kaniko/.docker/config.json
    - if [ $CI_COMMIT_REF_NAME == "develop" ];
        then /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination lotta/api:$CI_COMMIT_SHA --destination lotta/api:staging;
        elif [ $CI_COMMIT_REF_NAME == "master" ];
        then /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination lotta/api:$CI_COMMIT_SHA --destination lotta/api:stable --destination lotta/api:latest;
        else /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination lotta/api:$CI_COMMIT_SHA;
        fi

deploy staging:
  stage: deploy
  environment:
    name: staging
  image:
    name: lotta/do-helm-deploy:latest
  script:
    - /user/local/bin/setup.sh
    - helm repo add lotta https://medienportal.gitlab.io/helm-charts
    - helm repo update
    - helm upgrade --install lotta-api lotta/lotta-api
      --namespace lotta-staging
      --set image.pullPolicy=Always
      --set appEnvironment=staging
      --set loadFromBackup=true
      --set baseUrl=.staging.lotta.schule
      --set image.tag=$CI_COMMIT_SHA
      --set replicaCount=1
      --set jwtSecret=$JWT_SECRET
      --set liveViewSaltSecret=$LIVE_VIEW_SALT_SECRET
      --set liveView.username=lotta
      --set liveView.password=$LIVE_VIEW_PASSWORD
      --set baseSecret=$BASE_SECRET
      --set honeybadger.enabled=true
      --set honeybadger.apiKey=$HONEYBADGER_API_KEY
      --set s3Compat.endpoint=$S3COMPAT_ENDPOINT
      --set s3Compat.accessKeyId=$S3COMPAT_ACCESS_KEY_ID
      --set s3Compat.secretAccessKey=$S3COMPAT_SECRET_ACCESS_KEY
      --set s3Compat.bucket=$S3COMPAT_BUCKET
      --set s3Compat.region=$S3COMPAT_REGION
      --set s3Compat.cdnBaseUrl=$S3COMPAT_CDN_BASE_URL
      --set url=api.staging.lotta.schule
      --set ingress.enabled=true
      --set-string ingress.annotations."kubernetes\.io/ingress\.class"="nginx"
      --set-string ingress.annotations."nginx\.ingress\.kubernetes\.io/configuration-snippet"="proxy_set_header l5d-dst-override \\\$service_name.\\\$namespace.svc.cluster.local:\\\$service_port;grpc_set_header l5d-dst-override \\\$service_name.\\\$namespace.svc.cluster.local:\\\$service_port;"
      --set-string ingress.annotations."nginx\.ingress\.kubernetes\.io/proxy-body-size"="1500M"
      --set-string ingress.annotations."cert-manager\.io/cluster-issuer"="letsencrypt-production"
      --set ingress.hosts[0].host=*.staging.lotta.schule
      --set ingress.hosts[0].paths[0]=/api
      --set ingress.hosts[0].paths[1]=/sitemap.xml
      --set ingress.hosts[0].paths[1]=/dashboard
      --set ingress.tls[0].hosts[0]=*.staging.lotta.schule
      --set ingress.tls[0].secretName="lotta-web-staging-certificate"
      --set postgresql.postgresqlDatabase=$POSTGRES_DB
      --set postgresql.postgresqlUsername=$POSTGRES_USER
      --set postgresql.postgresqlPassword=$POSTGRES_PASSWORD
      --set postgresql.postgresqlPostgresPassword=$POSTGRES_PASSWORD
      --set postgresql.replication.enabled=true
      --set postgresql.replication.user=$POSTGRES_REPLICATION_USER
      --set postgresql.replication.password=$POSTGRES_REPLICATION_PASSWORD
      --set postgresql.replication.slaveReplicas=1
      --set postgresql.replication.synchronousCommit="on"
      --set postgresql.replication.numSynchronousReplicas=1
      --set postgresql.metrics.enabled=true
      --set rabbitmq.url=$RABBITMQ_URL
      --set redis.password=$REDIS_PASSWORD
      --set redis.cluster.slaveCount=1
      --set redis.metrics.enabled=true
      --set resources.limits.cpu=200m
      --set resources.limits.memory=386Mi
      --set resources.requests.cpu=200m
      --set resources.requests.memory=256Mi
  only:
    refs:
      - develop

deploy production:
  stage: deploy
  environment:
    name: production
  image:
    name: lotta/do-helm-deploy:latest
  script:
    - /user/local/bin/setup.sh
    - helm repo add lotta https://medienportal.gitlab.io/helm-charts
    - helm repo update
    - helm upgrade --install lotta-api lotta/lotta-api
      --namespace lotta
      --set appEnvironment=production
      --set baseUrl=.lotta.schule
      --set image.tag=$CI_COMMIT_SHA
      --set replicaCount=1
      --set jwtSecret=$JWT_SECRET
      --set liveViewSaltSecret=$LIVE_VIEW_SALT_SECRET
      --set liveView.username=lotta
      --set liveView.password=$LIVE_VIEW_PASSWORD
      --set baseSecret=$BASE_SECRET
      --set honeybadger.enabled=true
      --set honeybadger.apiKey=$HONEYBADGER_API_KEY
      --set s3Compat.endpoint=$S3COMPAT_ENDPOINT
      --set s3Compat.accessKeyId=$S3COMPAT_ACCESS_KEY_ID
      --set s3Compat.secretAccessKey=$S3COMPAT_SECRET_ACCESS_KEY
      --set s3Compat.bucket=$S3COMPAT_BUCKET
      --set s3Compat.region=$S3COMPAT_REGION
      --set s3Compat.cdnBaseUrl=$S3COMPAT_CDN_BASE_URL
      --set url=api.lotta.schule
      --set ingress.enabled=true
      --set-string ingress.annotations."kubernetes\.io/ingress\.class"="nginx"
      --set-string ingress.annotations."nginx\.ingress\.kubernetes\.io/configuration-snippet"="proxy_set_header l5d-dst-override \\\$service_name.\\\$namespace.svc.cluster.local:\\\$service_port;grpc_set_header l5d-dst-override \\\$service_name.\\\$namespace.svc.cluster.local:\\\$service_port;"
      --set-string ingress.annotations."nginx\.ingress\.kubernetes\.io/proxy-body-size"="1500M"
      --set-string ingress.annotations."cert-manager\.io/cluster-issuer"="letsencrypt-production"
      --set ingress.hosts[0].host=*.lotta.schule
      --set ingress.hosts[0].paths[0]=/api
      --set ingress.hosts[0].paths[1]=/sitemap.xml
      --set ingress.hosts[0].paths[2]=/dashboard
      --set ingress.tls[0].hosts[0]=*.lotta.schule
      --set ingress.tls[0].secretName="lotta-web-certificate"
      --set postgresql.postgresqlDatabase=$POSTGRES_DB
      --set postgresql.postgresqlUsername=$POSTGRES_USER
      --set postgresql.postgresqlPassword=$POSTGRES_PASSWORD
      --set postgresql.postgresqlPostgresPassword=$POSTGRES_PASSWORD
      --set postgresql.replication.enabled=true
      --set postgresql.replication.user=$POSTGRES_REPLICATION_USER
      --set postgresql.replication.password=$POSTGRES_REPLICATION_PASSWORD
      --set postgresql.replication.slaveReplicas=1
      --set postgresql.replication.synchronousCommit="on"
      --set postgresql.replication.numSynchronousReplicas=1
      --set rabbitmq.url=$RABBITMQ_URL
      --set postgresql.backupJob.enabled=true
      --set-string postgresql.backupJob.s3Compat.hostBucket="\%(bucket)s\.fra1\.digitaloceanspaces\.com"
      --set postgresql.backupJob.s3Compat.bucketName=lotta-backup-data
      --set postgresql.backupJob.s3Compat.path="/postgres"
      --set redis.password=$REDIS_PASSWORD
      --set redis.cluster.slaveCount=1
      --set redis.metrics.enabled=false
      --set resources.limits.cpu=300m
      --set resources.limits.memory=1536Mi
      --set resources.requests.cpu=200m
      --set resources.requests.memory=384Mi
  only:
    refs:
      - master
