---
services:
  postgres:
    image: postgres:15.1
    command: -c 'max_connections=500'
    environment:
      POSTGRES_USER: lotta
      POSTGRES_PASSWORD: lotta
      POSTGRES_DB: lotta
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U lotta']
      interval: 20s
      timeout: 10s
      retries: 7

  redis:
    image: bitnamilegacy/redis:latest
    environment:
      - REDIS_PASSWORD=lotta
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 20s
      timeout: 10s
      retries: 7

  minio:
    image: bitnamilegacy/minio:2025.7.23-debian-12-r5
    ports:
      - '9100:9100'
      - '9101:9101'
    environment:
      MINIO_SERVER_URL: http://0.0.0.0:9100
      MINIO_API_PORT_NUMBER: '9100'
      MINIO_CONSOLE_PORT_NUMBER: '9101'
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniosecret
      MINIO_DEFAULT_BUCKETS: 'lotta-e2e:s3:*'
    user: root
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'curl -sf http://0.0.0.0:9100/minio/health/live || exit 1',
        ]
      interval: 20s
      timeout: 5s
      retries: 7

  minio-setup:
    image: bitnamilegacy/minio-client:2025.7.21-debian-12-r3
    depends_on:
      minio:
        condition: service_healthy
    restart: no
    environment:
      HOME: /tmp
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set dockerminio http://minio:9100 minio miniosecret;
      mc mb dockerminio/lotta-dev;
      mc anonymous set download dockerminio/lotta-dev;

      mc alias set dockerminio http://minio:9100 minio miniosecret;
      mc mb dockerminio/lotta-test;
      mc anonymous set download dockerminio/lotta-test;

      mc alias set dockerminio http://minio:9100 minio miniosecret;
      mc mb dockerminio/lotta-e2e;
      mc anonymous set download dockerminio/lotta-e2e;
      exit 0;
      "
