---
services:
  postgres:
    image: postgres:15.1
    environment:
      POSTGRES_USER: lotta
      POSTGRES_PASSWORD: lotta
      POSTGRES_DB: lotta

  redis:
    image: bitnami/redis:latest
    environment:
      - REDIS_PASSWORD=lotta

  rabbitmq:
    image: rabbitmq:3.12-management
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  minio:
    image: bitnami/minio:2024
    ports:
      - 9000:9000
    environment:
      MINIO_SERVER_URL: http://localhost:9000
      MINIO_ROOT_USER: AKIAIOSFODNN7EXAMPLE
      MINIO_ROOT_PASSWORD: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      MINIO_DEFAULT_BUCKETS: 'lotta-dev-ugc:s3:*'
