---
version: "3.8"

services:
  postgres:
    image: postgres:15.1
    volumes:
      - ./_data/postgres:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
      - "5433:5433"
    environment:
      POSTGRES_USER: lotta
      POSTGRES_PASSWORD: lotta
      POSTGRES_DB: lotta

  redis:
    image: bitnami/redis:latest
    environment:
      - REDIS_PASSWORD=lotta
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3.12-management
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"

  minio:
    image: minio/minio
    command: server /data
    volumes:
      - ./_data/minio:/data
    environment:
      - MINIO_ROOT_USER=AKIAIOSFODNN7EXAMPLE
      - MINIO_ROOT_PASSWORD=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    ports:
      - 9000:9000

  minio-console:
    image: minio/console
    command: server
    environment:
      - CONSOLE_MINIO_SERVER=http://minio:9000
    ports:
      - 9090:9090
