---
version: "3.8"

services:
  postgres:
    image: postgres:11.12
    volumes:
      - ./_data/postgres:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
      - "5433:5433"
    environment:
      POSTGRES_USER: lotta
      POSTGRES_PASSWORD: lotta
      POSTGRES_DB: lotta

  redis:
    image: bitnami/redis:latest
    environment:
      - REDIS_PASSWORD=lotta
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3.7-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    # volumes:
    #   - /usr/share/elasticsearch/data
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK

  minio:
    image: minio/minio
    command: server /data
    volumes:
      - ./_data/minio:/data
    environment:
      - MINIO_ROOT_USER=AKIAIOSFODNN7EXAMPLE
      - MINIO_ROOT_PASSWORD=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    ports:
      - 9000:9000

  minio-console:
    image: minio/console
    command: server
    environment:
      - CONSOLE_MINIO_SERVER=http://minio:9000
    ports:
      - 9090:9090

  kibana:
    image: docker.elastic.co/kibana/kibana:7.7.0
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      SERVER_HOST: 0.0.0.0
