version: "3.7"

services:
  app:
    environment:
      MIX_ENV: test

  postgres:
    volumes:
      - ./_data/postgres-test:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: lotta_api

  redis:
    volumes:
      - ./_test/redis:/bitnami/redis/data
