version: "3.7"

services:
  app:
    environment:
      - "MIX_ENV=test"
      - "APP_ENVIRONMENT=test"
      - "UGC_S3_COMPAT_ENDPOINT=mp4-dev-ugc.fra1.digitalocean.com"
      - "UGC_S3_COMPAT_BUCKET=mp4-dev-ugc"

  postgres:
    volumes:
      - ./_test/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: lotta_api

  redis:
    volumes:
      - ./_test/redis:/bitnami/redis/data

  elasticsearch:
    volumes:
      - ./_test/elasticsearch:/usr/share/elasticsearch/data
