version: "3.7"

networks:
  api:
    driver: bridge
  postgres:
  rabbitmq:
    driver: bridge

volumes:
  elixir-mix:

services:
  app:
    image: elixir:1.9.2
    volumes:
      - .:/usr/src/svc
      - elixir-mix:/root/.mix
    working_dir: /usr/src/svc
    ports:
      - 4000:4000
    command: mix phx.server
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - api
      - postgres
      - rabbitmq
    environment:
      MIX_ENV: dev
    env_file:
      - .env

  postgres:
    image: postgres:11
    volumes:
      - ./_postgres-data:/var/lib/postgresql/data
    restart: always
    networks:
      - postgres
      - rabbitmq
    environment:
      POSTGRES_USER: lotta
      POSTGRES_PASSWORD: lotta
      POSTGRES_DB: lotta

  rabbitmq:
    image: rabbitmq:3.7-management
    hostname: rabbitmq
    networks:
      - rabbitmq
    expose:
      - "15672"
