version: "3.7"

networks:
  api:
    driver: bridge
  postgres:
    driver: bridge
  redis:
  elasticsearch:
    driver: bridge
  rabbitmq:
    driver: bridge

volumes:
  elixir-mix:

services:

  app:
    image: elixir:1.10.2
    volumes:
      - .:/usr/src/svc
      - elixir-mix:/root/.mix
    working_dir: /usr/src/svc
    ports:
      - 4000:4000
    command: iex -S mix phx.server
    depends_on:
      - rabbitmq
      - postgres
      - redis
      - elasticsearch
    networks:
      - api
      - postgres
      - rabbitmq
      - redis
      - elasticsearch
    environment:
      MIX_ENV: dev
    env_file:
      - .env
    tty: true
    stdin_open: true


  postgres:
    image: postgres:11
    volumes:
      - ./_data/postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - postgres
    environment:
      POSTGRES_USER: lotta
      POSTGRES_PASSWORD: lotta
      POSTGRES_DB: lotta


  redis:
    image: bitnami/redis:latest
    environment:
      - REDIS_PASSWORD=lotta
    networks:
      - redis
    volumes:
      - ./_data/redis:/bitnami/redis/data

  rabbitmq:
    image: rabbitmq:3.7-management
    hostname: rabbitmq
    networks:
      - rabbitmq
    ports:
      - "15672:15672"



  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    volumes:
      - ./_data/elasticsearch:/usr/share/elasticsearch/data
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    networks:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.7.0
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      SERVER_HOST: 0.0.0.0
    networks:
      - elasticsearch
