stages:
  - test
  - build
  - deploy

variables:
  # set docker host to connect to docker in kubernetes
  # DOCKER_HOST: tcp://localhost:2375/
  # DOCKER_DRIVER: overlay2
  # TODO: Set correct certs dir to /certs according to this article: https://about.gitlab.com/2019/07/31/docker-in-docker-with-docker-19-dot-03/
  DOCKER_TLS_CERTDIR: "/certs"

cache:
  key: "lotta-web-node-modules"
  paths:
    - node_modules/

test:
  stage: test
  image: node:14
  script:
    - npm install
    - npm run test:ci -- --coverage
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'

lint:
  stage: test
  image: node:14
  script:
    - npm install
    - npm run lint -- --max-warnings=0


build docker image:review:
  image: docker:19.03.0
  services:
    - docker:19.03.0-dind
  stage: build
  environment:
    name: review/$CI_COMMIT_REF_NAME
  script:
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USER" --password-stdin
    - docker pull lotta/web:staging
    - docker build -t lotta/web:$CI_COMMIT_SHA
      --build-arg APP_ENVIRONMENT=review/$CI_COMMIT_REF_NAME
      --build-arg APP_REVISION=$CI_COMMIT_SHA
      --build-arg APP_BASE_DOMAIN=.$CI_ENVIRONMENT_SLUG.lotta.schule
      --build-arg API_URL
      --build-arg AUTH_URL
      --build-arg AUTHENTICATION_TOKEN_NAME
      --build-arg CLOUDIMG_TOKEN
      --build-arg SENTRY_DSN
      --build-arg MATOMO_URL=""
      --build-arg MATOMO_SITEID=""
      --build-arg FILE_REPLACEMENT_URL="" .
    - docker tag lotta/web:$CI_COMMIT_SHA lotta/web:$CI_ENVIRONMENT_SLUG
    - docker push lotta/web
  except:
    refs:
      - develop
      - master

build docker image:staging:
  image: docker:19.03.0
  services:
    - docker:19.03.0-dind
  stage: build
  environment:
    name: staging
  script:
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USER" --password-stdin
    - docker pull lotta/web:staging
    - docker build -t lotta/web:$CI_COMMIT_SHA
      --build-arg APP_ENVIRONMENT=staging
      --build-arg APP_REVISION=$CI_COMMIT_SHA
      --build-arg APP_BASE_DOMAIN
      --build-arg API_URL="/api"
      --build-arg AUTH_URL="/auth"
      --build-arg CLOUDIMG_TOKEN
      --build-arg SENTRY_DSN
      --build-arg FILE_REPLACEMENT_URL .
    - docker tag lotta/web:$CI_COMMIT_SHA lotta/web:staging
    - docker push lotta/web
  only:
    refs:
      - develop

build docker image:production:
  image: docker:19.03.0
  services:
    - docker:19.03.0-dind
  stage: build
  environment:
    name: production
  script:
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USER" --password-stdin
    - docker pull lotta/web:production
    - docker build -t lotta/web:$CI_COMMIT_SHA
      --build-arg APP_ENVIRONMENT=production
      --build-arg APP_REVISION=$CI_COMMIT_SHA
      --build-arg APP_BASE_DOMAIN
      --build-arg API_URL="/api"
      --build-arg AUTH_URL="/auth"
      --build-arg CLOUDIMG_TOKEN
      --build-arg SENTRY_DSN
      --build-arg FILE_REPLACEMENT_URL .
    - docker tag lotta/web:$CI_COMMIT_SHA lotta/web:production
    - docker push lotta/web
  only:
    refs:
      - master
