packages:
  - libs/*
  - apps/*

catalog:
  '@absinthe/socket': ^0.2.1
  '@absinthe/socket-apollo-link': ^0.2.1
  '@apollo/client': ^4.0.11
  '@apollo/client-integration-nextjs': ^0.14.3
  '@dnd-kit/core': ^6.3.1
  '@dnd-kit/sortable': ^10.0.0
  '@dnd-kit/utilities': ^3.2.2
  '@epic-web/invariant': ^1.0.0
  '@eslint/compat': ^2.0.0
  '@eslint/js': ^9.39.2
  '@floating-ui/react': ^0.27.16
  '@fortawesome/fontawesome-svg-core': ^7.1.0
  '@fortawesome/free-regular-svg-icons': ^7.1.0
  '@fortawesome/free-solid-svg-icons': ^7.1.0
  '@fortawesome/react-fontawesome': ^3.1.1
  '@next/eslint-plugin-next': ^16.0.10
  '@nx/js': 22.3.1
  '@nx/workspace': 22.3.1
  '@playwright/test': ^1.57.0
  '@ptitmouton/app-config': ^0.0.2
  '@react-types/checkbox': ^3.10.2
  '@react-types/progress': ^3.5.16
  '@react-types/shared': ^3.32.1
  '@rollup/plugin-graphql': ^2.0.4
  '@storybook/addon-a11y': ^10.1.10
  '@storybook/addon-coverage': ^3.0.0
  '@storybook/addon-docs': ^10.1.10
  '@storybook/addon-links': ^10.1.10
  '@storybook/addon-themes': ^10.1.10
  '@storybook/react': ^10.1.10
  '@storybook/react-vite': ^10.1.10
  '@storybook/test': ^8.6.14
  '@storybook/test-runner': ^0.24.2
  '@swc-node/register': ~1.11.1
  '@swc/core': ~1.15.6
  '@swc/helpers': ~0.5.17
  '@testing-library/jest-dom': ^6.9.1
  '@testing-library/react': ^16.3.1
  '@testing-library/user-event': ^14.6.1
  '@types/absinthe__socket': ^0.2.6
  '@types/absinthe__socket-apollo-link': ^0.2.1
  '@types/cookies': ^0.9.2
  '@types/file-saver': ^2.0.7
  '@types/is-url': ^1.2.32
  '@types/lodash': ^4.17.21
  '@types/node': ^25.0.3
  '@types/phoenix': ^1.6.7
  '@types/react': ^19.2.7
  '@types/react-big-calendar': ^1.16.3
  '@types/react-dom': ^19.2.3
  '@types/slate-base64-serializer': ^0.2.5
  '@types/user-event': ^4.1.3
  '@vercel/otel': ^2.1.0
  '@vitejs/plugin-react': ^5.1.2
  '@vitest/browser': ^4.0.16
  '@vitest/browser-playwright': ^4.0.16
  '@vitest/coverage-istanbul': ^4.0.16
  '@vitest/ui': ^4.0.16
  apollo-v3-absinthe-upload-link: ^1.6.0
  axios: ^1.13.2
  chromatic: ^13.3.4
  chromium-bidi: ^12.0.1
  clsx: ^2.1.1
  colorjs.io: ^0.5.2
  concurrently: ^9.2.1
  cookie-es: ^2.0.0
  cookies: ^0.9.1
  date-fns: ^3.6.0
  eslint: ^9.39.2
  eslint-config-next: ^16.0.10
  eslint-config-prettier: ^10.1.8
  eslint-plugin-import: ^2.32.0
  eslint-plugin-prettier: ^5.5.4
  eslint-plugin-promise: ^7.0.0
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-compiler: ^19.1.0-rc.2
  eslint-plugin-react-hooks: ^7.0.1
  eslint-plugin-storybook: ^10.1.10
  eslint-plugin-testing-library: ^7.15.1
  eslint-plugin-vitest: 0.5.4
  file-saver: ^2.0.5
  framer-motion: ^12.23.26
  gql.tada: ^1.9.0
  graphql: ^16.12.0
  graphql-tag: ^2.12.6
  http-proxy-middleware: ^3.0.5
  http-server: ^14.1.1
  husky: ^9.1.3
  i18next: ^25.7.3
  i18next-parser: ^9.3.0
  ignore-loader: ^0.1.2
  import-in-the-middle: ^2.0.0
  is-url: ^1.2.4
  jsdom: ^27.3.0
  jwt-decode: ^4.0.0
  lerna: ^9.0.3
  lint-staged: ^16.2.7
  lodash: ^4.17.21
  next: 16.0.10
  nx: 22.3.1
  phoenix: ^1.8.3
  playwright: ^1.57.0
  prettier: ^3.7.4
  react: ^19.2.3
  react-aria: ^3.45.0
  react-big-calendar: ^1.19.4
  react-charts: 3.0.0-beta.57
  react-dom: ^19.2.3
  react-dropzone: ^14.3.8
  react-i18next: ^16.5.0
  react-stately: ^3.43.0
  react-use: ^17.6.0
  recharts: ^3.6.0
  require-in-the-middle: ^8.0.1
  sass: ^1.97.0
  slate: ^0.76.1
  slate-react: ^0.76.1
  slugify: ^1.6.6
  storybook: ^10.1.10
  tsup: ^8.5.1
  typescript: ^5.9.3
  typescript-eslint: ^8.50.0
  vite: ^7.3.0
  vite-plugin-dts: 4.5.4
  vite-plugin-externalize-deps: ^0.10.0
  vite-tsconfig-paths: ^6.0.3
  vitest: ^4.0.16
  wait-on: ^9.0.3
