---
name: Build

on:
  workflow_run:
    workflows:
      - Test
    types:
      - completed
    branches:
      - main
      - hotfix/**

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

  build:
    needs:
      - setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build docker image
        run: docker build -t ghcr.io/${{ github.repository }}:$GITHUB_SHA .

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: push image to registry
        run: |
          docker tag ghcr.io/${{ github.repository }}:$GITHUB_SHA ghcr.io/${{ github.repository }}:develop
          docker push ghcr.io/${{ github.repository }}:$GITHUB_SHA
          docker push ghcr.io/${{ github.repository }}:develop

      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: core
        with:
          environment: staging
          version: ${{ github.sha }}
