---
name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        options: >-
          -e POSTGRES_USER=lotta
          -e POSTGRES_PASSWORD=lotta
      rabbitmq:
        image: rabbitmq:latest
        ports:
          - 5672:5672
      redis:
        image: bitnami/redis:latest
        ports:
          - 6379:6379
        options: >-
          -e REDIS_PASSWORD=lotta
      minio:
        image: bitnami/minio:latest
        ports:
          - 9000:9000
        options: >-
          -e MINIO_ROOT_USER="AKIAIOSFODNN7EXAMPLE"
          -e MINIO_ROOT_PASSWORD="wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
          -e MINIO_DEFAULT_BUCKETS="lotta-dev-ugc"
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
        ports:
          - 9200:9200
        options: >-
          -e discovery.type=single-node
          -e xpack.security.enabled=false

    steps:
      - uses: actions/checkout@v3

      - uses: erlef/setup-beam@v1
        with:
          otp-version: "25.2"
          elixir-version: "1.14.2"

      - name: Install test dependencies
        run: mix deps.get --only test

      - name: Run tests
        run: |
          mix test --except creates_tenant --cover
        env:
          MIX_ENV: test

      - name: Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: _build/test/lib/lotta
          # fail_ci_if_error: true

  compile:
    name: Make sure it compiles
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: erlef/setup-beam@v1
        name: Setup Elixir
        with:
          otp-version: "25.2"
          elixir-version: "1.14.2"

      - name: Get dependencies
        run: mix deps.get

      - name: compile
        run: mix compile --force

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: erlef/setup-beam@v1
        name: Setup Elixir
        with:
          otp-version: "25.2"
          elixir-version: "1.14.2"

      - name: Get dependencies
        run: mix deps.get

      - name: check visual code-style
        run: mix format --check-formatted

      - name: check code quality
        run: mix credo -a
