---
name: 'Deploy npm packages'

on:
  workflow_call:
    inputs:
      checkout-ref:
        description: Ref to checkout the repository at
        type: string
        required: false
    secrets:
      npm-token:
        required: true
    outputs:
      version-name:
        description: 'The version of the package, as read from lerna.json'
        value: ${{ jobs.push-packages.outputs.version-name }}
      tag-name:
        description: 'The tag, can be latest or alpha'
        value: ${{ jobs.push-packages.outputs.tag-name }}

jobs:
  push-packages:
    name: 'Push npm packages to registry'
    runs-on: ubuntu-latest
    outputs:
      version-name: ${{ steps.publish.outputs.version-name }}
      tag-name: ${{ steps.publish.outputs.tag-name }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ inputs.checkout-ref }}

      - name: Setup NX
        uses: nrwl/nx-set-shas@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version: 20
          cache: 'npm'

      - name: Install npm dependencies
        run: npm ci

      - name: Run build task
        run: npm run nx run-many -- -t build

      - name: Publish to npm
        id: publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm-token }}
        run: |
          tag='latest'
          version=$(cat lerna.json | jq -r .version)
          if [[ $version == *'-'* ]]; then
            tag=$(echo $version | sed -E 's/^.*-([a-z]*).*/\1/')
          fi
          npm -w @lotta-schule/theme publish --tag $tag
          npm -w @lotta-schule/hubert publish --tag $tag
          npm -w @lotta-schule/storybook-addon-theme publish --tag $tag
          echo "version-name=$version" >> $GITHUB_OUTPUT
          echo "tag-name=$tag" >> $GITHUB_OUTPUT
          echo "Outputting version-name ($version) and tag-name ($tag) to github output"
