---
name: 'Deploy npm packages'

on:
  workflow_call:
    inputs:
      base_sha:
        type: string
        required: true
      head_sha:
        type: string
        required: true
    secrets:
      npm-token:
        required: true

jobs:
  push-packages:
    name: 'Push npm packages to registry'
    runs-on: ubuntu-latest
    env:
      NX_BASE: '${{ inputs.base_sha }}'
      NX_HEAD: '${{ inputs.head_sha }}'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version: 20
          cache: 'npm'

      - name: Install npm dependencies
        run: npm ci

      - name: Run build task
        run: npx nx run-many -t build

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm-token }}
        run: |
          tag='latest'
          version=$(cat lerna.json | jq -r .version)
          if [[ $version == *'-'* ]]; then
            tag=$(echo $version | sed -E 's/^.*-([a-z]*).*/\1/')
          fi
          npm -w @lotta-schule/theme publish --tag $tag
          npm -w @lotta-schule/hubert publish --tag $tag
          npm -w @lotta-schule/storybook-addon-theme publish --tag $tag
