---
name: 'Deploy npm packages'

on:
  workflow_call:
    secrets:
      npm-token:
        required: true
    outputs:
      version_name:
        description: 'The version of the package, as read from lerna.json'
        value: ${{ jobs.publish.outputs.version_name }}
      tag_name:
        description: 'The tag, can be latest or alpha'
        value: ${{ jobs.publish.outputs.tag_name }}

jobs:
  push-packages:
    name: 'Push npm packages to registry'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup NX
        uses: nrwl/nx-set-shas@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version: 20
          cache: 'npm'

      - name: Install npm dependencies
        run: npm ci

      - name: Run build task
        run: npx nx run-many -t build

      - name: Publish to npm
        id: publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm-token }}
        run: |
          tag='latest'
          version=$(cat lerna.json | jq -r .version)
          if [[ $version == *'-'* ]]; then
            tag=$(echo $version | sed -E 's/^.*-([a-z]*).*/\1/')
          fi
          npm -w @lotta-schule/theme publish --tag $tag
          npm -w @lotta-schule/hubert publish --tag $tag
          npm -w @lotta-schule/storybook-addon-theme publish --tag $tag
          echo "version_name=$version" >> $GITHUB_OUTPUT
          echo "tag_name=$tag" >> $GITHUB_OUTPUT
