---
name: build

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

  build:
    needs:
      - setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build docker image
        env:
          IMAGE_NAME: ghcr.io/${{ github.repository }}:${{ github.sha }}
        run: docker build --build-arg IMAGE_NAME -t $IMAGE_NAME .

      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: push image to registry
        run: |
          docker tag ghcr.io/${{ github.repository }}:$GITHUB_SHA ghcr.io/${{ github.repository }}:develop
          docker push ghcr.io/${{ github.repository }}:$GITHUB_SHA
          docker push ghcr.io/${{ github.repository }}:develop

      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: web
        with:
          environment: staging
          version: ${{ github.sha }}
