---
name: 'CI'
on:
  push:
env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
  lint-test:
    name: Lint Code and run tests
    runs-on: ubuntu-latest
    if: "${{ !startsWith(github.event.head_commit.message, 'chore(release): publish') }}"
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup main branch for reference
        if: ${{ github.ref_name != 'main' }}
        run: git branch --track main origin/main

      - name: Setup NX
        uses: nrwl/nx-set-shas@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install npm dependencies
        run: npm ci

      - name: Lint
        run: npx nx affected -t lint

      - name: Typecheck
        run: npx nx affected -t typecheck

      - name: Run tests
        run: npx nx affected -t test --ci --collectCoverage --configuration=ci

      - name: Run end-to-end tests
        run: npx nx affected -t e2e --configuration=ci

      - name: Upload Tests for storybook-addon-theme
        uses: codecov/codecov-action@v2
        with:
          working-directory: packages/storybook-addon-theme/
          directory: coverage/
          flags: storybook-addon-theme
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

      - name: Upload Tests for hubert
        uses: codecov/codecov-action@v2
        with:
          working-directory: packages/hubert/
          directory: coverage/
          flags: hubert
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

      - name: Upload Tests for hubert storybook
        uses: codecov/codecov-action@v2
        with:
          working-directory: packages/storybook-hubert/
          directory: coverage/
          flags: storybook-hubert
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

      - name: Upload Tests for Webapp
        uses: codecov/codecov-action@v2
        with:
          working-directory: packages/webapp/
          directory: coverage/
          flags: webapp
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

      - name: Bump version if on main
        # TODO: Comment back when tested!
        # if: ${{ github.ref_name == 'main' }}
        run: |
          npx lerna version --conventional-prerelease --preid alpha --allow-branch=feature/monoorepo -y
