name: 'Auto Assign Reviewer'
on:
  pull_request_target:
    types: [opened, ready_for_review]

jobs:
  add-reviews:
    runs-on: ubuntu-24.04
    steps:
      - uses: kentaro-m/auto-assign-action@v2.0.0
